from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications.densenet import preprocess_input
'''
项目数据集配置文件
'''
food_config = {
    "dataset_name":"food",
    "merged_df_path":"/data/mml/overlap_v2_datasets/food/merged_data/test/merged_df.csv",
    "merged_train_df":"/data/mml/overlap_v2_datasets/food/merged_data/train/merged_df.csv",
    "df_eval_party_A_path":"/data/mml/overlap_v2_datasets/food/party_A/dataset_split/val.csv",
    "df_eval_party_B_path":"/data/mml/overlap_v2_datasets/food/party_B/dataset_split/val.csv",
    "generator_A":ImageDataGenerator(horizontal_flip=True,rotation_range=20, width_shift_range=.2,height_shift_range=.2, zoom_range=.2),
    "generator_B":ImageDataGenerator(rescale = 1./255),
    "generator_A_test":ImageDataGenerator(),
    "generator_B_test":ImageDataGenerator(rescale = 1./255),
    "target_size_A":(256,256),
    "target_size_B":(224,224),
    "model_A_struct_path":"/data/mml/overlap_v2_datasets/food/party_A/models/model_struct/EfficientNetB3.h5",
    "model_A_weight_path":"/data/mml/overlap_v2_datasets/food/party_A/models/model_weights/model_weight_013_0.9061.h5",
    "model_B_struct_path":"/data/mml/overlap_v2_datasets/food/party_B/models/model_struct/VGG19.h5",
    "model_B_weight_path":"/data/mml/overlap_v2_datasets/food/party_B/models/model_weights/model_weight_012_0.9132.h5",
    "local_to_global_party_A_path":"exp_data/food/LocalToGlobal/local_to_global_party_A.data",
    "local_to_global_party_B_path":"exp_data/food/LocalToGlobal/local_to_global_party_B.data",
    "dataset_A_train_path":"/data/mml/overlap_v2_datasets/food/party_A/dataset_split/train",
    "dataset_B_train_path":"/data/mml/overlap_v2_datasets/food/party_B/dataset_split/train",
    "sampled_common_path":"exp_data/food/sampling/num/random",
    "combination_model_path":"/data/mml/overlap_v2_datasets/food/merged_model/combination_model_inheritWeights.h5",
    "stu_model_path":"/data/mml/overlap_v2_datasets/food/merged_model/DenseNet121_224_224_claNum_12.h5",
    "combiantion_lr":0.00003,
    "save_retrainResult_path":"exp_data/food/retrainResult/num/CFL",
}

fruit_config = {
    "dataset_name":"Fruit",
    "merged_df_path":"/data/mml/overlap_v2_datasets/Fruit/merged_data/test/merged_df.csv",
    "merged_train_df":"/data/mml/overlap_v2_datasets/Fruit/merged_data/train/merged_df.csv",
    "df_eval_party_A_path":"/data/mml/overlap_v2_datasets/Fruit/party_A/dataset_split/val.csv",
    "df_eval_party_B_path":"/data/mml/overlap_v2_datasets/Fruit/party_B/dataset_split/val.csv",
    "generator_A":ImageDataGenerator(rescale = 1./255, rotation_range=20, width_shift_range=.2,height_shift_range=.2, zoom_range=.2),
    "generator_B":ImageDataGenerator(rescale = 1./255),
    "generator_A_test":ImageDataGenerator(rescale = 1./255),
    "generator_B_test":ImageDataGenerator(rescale = 1./255),
    "target_size_A":(224,224),
    "target_size_B":(224,224),
    "model_A_struct_path":"/data/mml/overlap_v2_datasets/Fruit/party_A/models/model_struct/VGG19.h5",
    "model_A_weight_path":"/data/mml/overlap_v2_datasets/Fruit/party_A/models/model_weights/model_weight_020_0.8636.h5",
    "model_B_struct_path":"/data/mml/overlap_v2_datasets/Fruit/party_B/models/model_struct/Xception.h5",
    "model_B_weight_path":"/data/mml/overlap_v2_datasets/Fruit/party_B/models/model_weights/model_weight_022_0.9759.h5",
    "local_to_global_party_A_path":"exp_data/Fruit/LocalToGlobal/local_to_global_party_A.data",
    "local_to_global_party_B_path":"exp_data/Fruit/LocalToGlobal/local_to_global_party_B.data",
    "dataset_A_train_path":"/data/mml/overlap_v2_datasets/Fruit/party_A/dataset_split/train",
    "dataset_B_train_path":"/data/mml/overlap_v2_datasets/Fruit/party_B/dataset_split/train",
    "sampled_common_path":"exp_data/Fruit/sampling/num/random",
    "combination_model_path":"/data/mml/overlap_v2_datasets/Fruit/merged_model/combination_model_inheritWeights.h5",
    "stu_model_path":"/data/mml/overlap_v2_datasets/Fruit/merged_model/DenseNet121_224_224_claNum_16.h5",
    "combiantion_lr":0.0003,
    "save_retrainResult_path":"exp_data/Fruit/retrainResult/num/CFL"
}

sport_config = {
    "dataset_name":"sport",
    "merged_df_path":"/data/mml/overlap_v2_datasets/sport/merged_data/test/merged_df.csv",
    "merged_train_df":"/data/mml/overlap_v2_datasets/sport/merged_data/train/merged_df.csv",
    "df_eval_party_A_path":"/data/mml/overlap_v2_datasets/sport/party_A/dataset_split/val.csv",
    "df_eval_party_B_path":"/data/mml/overlap_v2_datasets/sport/party_B/dataset_split/val.csv",
    "generator_A":ImageDataGenerator(horizontal_flip=True,rotation_range=20, width_shift_range=.2, height_shift_range=.2, zoom_range=.2),
    "generator_B":ImageDataGenerator(rescale=1./255, zoom_range=0.5,horizontal_flip=True,rotation_range=40,vertical_flip=0.5,width_shift_range=0.3,height_shift_range=0.2,brightness_range=[0.2,1.0],fill_mode='nearest'),
    "generator_A_test":ImageDataGenerator(),
    "generator_B_test":ImageDataGenerator(rescale = 1./255),
    "target_size_A":(224,224),
    "target_size_B":(224,224),
    "model_A_struct_path":"/data/mml/overlap_v2_datasets/sport/party_A/models/model_struct/EfficientNetB3.h5",
    "model_A_weight_path":"/data/mml/overlap_v2_datasets/sport/party_A/models/model_weights/model_weight_031_0.9453.h5",
    "model_B_struct_path":"/data/mml/overlap_v2_datasets/sport/party_B/models/provided_models/vgg16.h5",
    "model_B_weight_path":None,
    "local_to_global_party_A_path":"exp_data/sport/LocalToGlobal/local_to_gobal_party_A.data",
    "local_to_global_party_B_path":"exp_data/sport/LocalToGlobal/local_to_gobal_party_B.data",
    "dataset_A_train_path":"/data/mml/overlap_v2_datasets/sport/party_A/dataset_split/train",
    "dataset_B_train_path":"/data/mml/overlap_v2_datasets/sport/party_B/dataset_split/train",
    "sampled_common_path":"exp_data/sport/sampling/num/random",
    "combination_model_path":"/data/mml/overlap_v2_datasets/sport/merged_model/combination_model_inheritWeights.h5",
    "stu_model_path":"/data/mml/overlap_v2_datasets/sport/merged_model/DenseNet121_224_224_claNum_109.h5",
    "combiantion_lr":0.00003,
    "save_retrainResult_path":"exp_data/sport/retrainResult/num/CFL"
}

weather_config = {
    "dataset_name":"weather",
    "merged_df_path":"/data/mml/overlap_v2_datasets/weather/merged_data/test/merged_df.csv",
    "merged_train_df":"/data/mml/overlap_v2_datasets/weather/merged_data/train/merged_df.csv",
    "df_eval_party_A_path":"/data/mml/overlap_v2_datasets/weather/party_A/dataset_split/val.csv",
    "df_eval_party_B_path":"/data/mml/overlap_v2_datasets/weather/party_B/dataset_split/val.csv",
    "generator_A":ImageDataGenerator(horizontal_flip=True,vertical_flip=True,rotation_range=10,width_shift_range=0.2,height_shift_range=0.2,zoom_range=.2),
    "generator_B":ImageDataGenerator(rescale=1./255,horizontal_flip=True,rotation_range=10),
    "generator_A_test":ImageDataGenerator(),
    "generator_B_test":ImageDataGenerator(rescale = 1./255),
    "target_size_A":(100,100),
    "target_size_B":(256,256),
    "model_A_struct_path":"/data/mml/overlap_v2_datasets/weather/party_A/models/model_struct/vgg19.h5",
    "model_A_weight_path":"/data/mml/overlap_v2_datasets/weather/party_A/models/model_weights/model_weight_050_0.8254.h5",
    "model_B_struct_path":"/data/mml/overlap_v2_datasets/weather/party_B/models/model_struct/ResNet152V2.h5",
    "model_B_weight_path":"/data/mml/overlap_v2_datasets/weather/party_B/models/model_weights/model_weight_049_0.8969.h5",
    "local_to_global_party_A_path":"exp_data/weather/LocalToGlobal/local_to_gobal_party_A.data",
    "local_to_global_party_B_path":"exp_data/weather/LocalToGlobal/local_to_gobal_party_B.data",
    "dataset_A_train_path":"/data/mml/overlap_v2_datasets/weather/party_A/dataset_split/train",
    "dataset_B_train_path":"/data/mml/overlap_v2_datasets/weather/party_B/dataset_split/train",
    "sampled_common_path":"exp_data/weather/sampling/num/random",
    "combination_model_path":"/data/mml/overlap_v2_datasets/weather/merged_model/combination_model_inheritWeights.h5",
    "stu_model_path":"/data/mml/overlap_v2_datasets/weather/merged_model/DenseNet121_224_224_claNum_13.h5",
    "combiantion_lr":0.0003,
    "save_retrainResult_path":"exp_data/weather/retrainResult/num/CFL"
}

flower_2_config = {
    "dataset_name":"flower_2",
    "merged_df_path":"/data/mml/overlap_v2_datasets/flower_2/merged_data/test/merged_df.csv",
    "merged_train_df":"/data/mml/overlap_v2_datasets/flower_2/merged_data/train/merged_df.csv",
    "df_eval_party_A_path":"/data/mml/overlap_v2_datasets/flower_2/party_A/dataset_split/val.csv",
    "df_eval_party_B_path":"/data/mml/overlap_v2_datasets/flower_2/party_B/dataset_split/val.csv",
    "generator_A":ImageDataGenerator(rescale=1/255.,rotation_range=10, horizontal_flip=True,validation_split=0.2),
    "generator_B":ImageDataGenerator(preprocessing_function=preprocess_input,zoom_range=0.2,shear_range=0.2,vertical_flip=True,width_shift_range=0.2,height_shift_range=0.2,fill_mode='nearest',validation_split=0.2),
    "generator_A_test":ImageDataGenerator(rescale=1/255.),
    "generator_B_test":ImageDataGenerator(preprocessing_function=preprocess_input),
    "target_size_A":(256,256),
    "target_size_B":(331,331),
    "model_A_struct_path":"/data/mml/overlap_v2_datasets/flower_2/party_A/models/model_struct/ResNet50V2_256_256.h5",
    "model_A_weight_path":"/data/mml/overlap_v2_datasets/flower_2/party_A/models/model_weights/model_weight_042_0.9431.h5",
    "model_B_struct_path":"/data/mml/overlap_v2_datasets/flower_2/party_B/models/model_struct/DenseNet201_331_331_poolingAvg.h5",
    "model_B_weight_path":"/data/mml/overlap_v2_datasets/flower_2/party_B/models/model_weights/model_weight_013_0.9145.h5",
    "local_to_global_party_A_path":"exp_data/flower_2/LocalToGlobal/local_to_gobal_party_A.data",
    "local_to_global_party_B_path":"exp_data/flower_2/LocalToGlobal/local_to_gobal_party_B.data",
    "dataset_A_train_path":"/data/mml/overlap_v2_datasets/flower_2/party_A/dataset_split/train",
    "dataset_B_train_path":"/data/mml/overlap_v2_datasets/flower_2/party_B/dataset_split/train",
    "merged_train_df":"/data/mml/overlap_v2_datasets/flower_2/merged_data/train/merged_df.csv",
    "sampled_common_path":"exp_data/flower_2/sampling/num/random",
    "combination_model_path":"/data/mml/overlap_v2_datasets/flower_2/merged_model/combination_model_inheritWeights.h5",
    "stu_model_path":"/data/mml/overlap_v2_datasets/flower_2/merged_model/DenseNet121_224_224_claNum_7.h5",
    "combiantion_lr":0.0005,
    "save_retrainResult_path":"exp_data/flower_2/retrainResult/num/CFL"
}

car_body_style_config = {
    "dataset_name":"car_body_style",
    "merged_df_path":"/data/mml/overlap_v2_datasets/car_body_style/merged_data/test/merged_df.csv",
    "merged_train_df":"/data/mml/overlap_v2_datasets/car_body_style/merged_data/train/merged_df.csv",
    "df_eval_party_A_path":"/data/mml/overlap_v2_datasets/car_body_style/party_A/dataset_split/val.csv",
    "df_train_party_A_path":"/data/mml/overlap_v2_datasets/car_body_style/party_A/dataset_split/train.csv",
    "df_eval_party_B_path":"/data/mml/overlap_v2_datasets/car_body_style/party_B/dataset_split/val.csv",
    "generator_A":ImageDataGenerator(rescale=1./255,horizontal_flip=True,width_shift_range=0.15,height_shift_range=0.15,rotation_range=5,zoom_range=0.15),
    "generator_B":ImageDataGenerator(rescale=1./255,horizontal_flip=True,width_shift_range=0.15,height_shift_range=0.15,rotation_range=5,zoom_range=0.15),
    "generator_A_test":ImageDataGenerator(rescale=1./255),
    "generator_B_test":ImageDataGenerator(rescale=1./255),
    "target_size_A":(256,256),
    "target_size_B":(224,224),
    "model_A_struct_path":"/data/mml/overlap_v2_datasets/car_body_style/party_A/models/model_struct/Xception.h5",
    "model_A_weight_path":"/data/mml/overlap_v2_datasets/car_body_style/party_A/models/model_weights/model_weight_041_0.8352.h5",
    "model_B_struct_path":"/data/mml/overlap_v2_datasets/car_body_style/party_B/models/model_struct/Xception.h5",
    "model_B_weight_path":"/data/mml/overlap_v2_datasets/car_body_style/party_B/models/model_weights/model_weight_039_0.8464.h5",
    "local_to_global_party_A_path":"exp_data/car_body_style/LocalToGlobal/local_to_gobal_party_A.data",
    "local_to_global_party_B_path":"exp_data/car_body_style/LocalToGlobal/local_to_gobal_party_B.data",
    "dataset_A_train_path":"/data/mml/overlap_v2_datasets/car_body_style/party_A/dataset_split/train",
    "dataset_B_train_path":"/data/mml/overlap_v2_datasets/car_body_style/party_B/dataset_split/train",
    "sampled_common_path":"exp_data/car_body_style/sampling/num/random",
    "combination_model_path":"/data/mml/overlap_v2_datasets/car_body_style/merged_model/combination_model_inheritWeights.h5",
    "stu_model_path":"/data/mml/overlap_v2_datasets/car_body_style/merged_model/DenseNet121_224_224_claNum_10.h5",
    "combiantion_lr":0.0003,
    "save_retrainResult_path":"exp_data/car_body_style/retrainResult/num/CFL",
}

animal_config = {
    "dataset_name":"animal",
    "merged_df_path":"/data/mml/overlap_v2_datasets/animal/merged_data/test/merged_df.csv",
    "merged_train_df":"/data/mml/overlap_v2_datasets/animal/merged_data/train/merged_df.csv",
    "df_eval_party_A_path":"/data/mml/overlap_v2_datasets/animal/party_A/dataset_split/val.csv",
    "df_eval_party_B_path":"/data/mml/overlap_v2_datasets/animal/party_B/dataset_split/val.csv",
    "generator_A":ImageDataGenerator(rescale=1./255,horizontal_flip=True,width_shift_range=0.15,height_shift_range=0.15,rotation_range=5,zoom_range=0.15),
    "generator_B":ImageDataGenerator(rescale=1./255),
    "generator_A_test":ImageDataGenerator(rescale=1./255),
    "generator_B_test":ImageDataGenerator(rescale=1./255),
    "target_size_A":(224,224),
    "target_size_B":(150,150),
    "model_A_struct_path":"/data/mml/overlap_v2_datasets/animal/party_A/models/model_struct/VGG19.h5",
    "model_A_weight_path":"/data/mml/overlap_v2_datasets/animal/party_A/models/model_weights/model_weight_037_0.8875.h5",
    "model_B_struct_path":"/data/mml/overlap_v2_datasets/animal/party_B/models/model_struct/Xception.h5",
    "model_B_weight_path":"/data/mml/overlap_v2_datasets/animal/party_B/models/model_weights/model_weight_048_0.9035.h5",
    "local_to_global_party_A_path":"exp_data/animal/LocalToGlobal/local_to_gobal_party_A.data",
    "local_to_global_party_B_path":"exp_data/animal/LocalToGlobal/local_to_gobal_party_B.data",
    "dataset_A_train_path":"/data/mml/overlap_v2_datasets/animal/party_A/dataset_split/train",
    "dataset_B_train_path":"/data/mml/overlap_v2_datasets/animal/party_B/dataset_split/train",
    "sampled_common_path":"exp_data/animal/sampling/num/random",
    "combination_model_path":"/data/mml/overlap_v2_datasets/animal/merged_model/combination_model_inheritWeights.h5",
    "stu_model_path":"/data/mml/overlap_v2_datasets/animal/merged_model/DenseNet121_224_224_claNum_13.h5",
    "combiantion_lr":0.0003,
    "save_retrainResult_path":"exp_data/animal/retrainResult/num/CFL"
}

animal_2_config = {
    "dataset_name":"animal_2",
    "merged_df_path":"/data/mml/overlap_v2_datasets/animal_2/merged_data/test/merged_df.csv",
    "merged_train_df":"/data/mml/overlap_v2_datasets/animal_2/merged_data/train/merged_df.csv",
    "df_eval_party_A_path":"/data/mml/overlap_v2_datasets/animal_2/party_A/dataset_split/val.csv",
    "df_eval_party_B_path":"/data/mml/overlap_v2_datasets/animal_2/party_B/dataset_split/val.csv",
    "generator_A":ImageDataGenerator(fill_mode = 'nearest',validation_split=0.2),
    "generator_B":ImageDataGenerator(validation_split=0.2),
    "generator_A_test":ImageDataGenerator(),
    "generator_B_test":ImageDataGenerator(),
    "target_size_A":(108,108),
    "target_size_B":(64,64),
    "model_A_struct_path":"/data/mml/overlap_v2_datasets/animal_2/party_A/models/model_struct/ResNet50.h5",
    "model_A_weight_path":"/data/mml/overlap_v2_datasets/animal_2/party_A/models/model_weights/model_weight_009_0.9187.h5",
    "model_B_struct_path":"/data/mml/overlap_v2_datasets/animal_2/party_B/models/model_struct/EfficientNetB0.h5",
    "model_B_weight_path":"/data/mml/overlap_v2_datasets/animal_2/party_B/models/model_weights/model_weight_029_0.9396.h5",
    "local_to_global_party_A_path":"exp_data/animal_2/LocalToGlobal/local_to_gobal_party_A.data",
    "local_to_global_party_B_path":"exp_data/animal_2/LocalToGlobal/local_to_gobal_party_B.data",
    "dataset_A_train_path":"/data/mml/overlap_v2_datasets/animal_2/party_A/dataset_split/train",
    "dataset_B_train_path":"/data/mml/overlap_v2_datasets/animal_2/party_B/dataset_split/train",
    "sampled_common_path":"exp_data/animal_2/sampling/num/random",
    "combination_model_path":"/data/mml/overlap_v2_datasets/animal_2/merged_model/combination_model_inheritWeights.h5",
    "stu_model_path":"/data/mml/overlap_v2_datasets/animal_2/merged_model/DenseNet121_224_224_claNum_6.h5",
    "combiantion_lr":0.0005,
    "save_retrainResult_path":"exp_data/animal_2/retrainResult/num/CFL"
}

animal_3_config = {
    "dataset_name":"animal_3",
    "merged_df_path":"/data/mml/overlap_v2_datasets/animal_3/merged_data/test/merged_df.csv",
    "merged_train_df":"/data/mml/overlap_v2_datasets/animal_3/merged_data/train/merged_df.csv",
    "df_eval_party_A_path":"/data/mml/overlap_v2_datasets/animal_3/party_A/dataset_split/val.csv",
    "df_eval_party_B_path":"/data/mml/overlap_v2_datasets/animal_3/party_B/dataset_split/val.csv",
    "generator_A":ImageDataGenerator(horizontal_flip=True, rotation_range=20, width_shift_range=.2,height_shift_range=.2,zoom_range=.2,validation_split=0.2),
    "generator_B":ImageDataGenerator(horizontal_flip=True,  rotation_range=20, width_shift_range=.2,height_shift_range=.2, zoom_range=.2,validation_split=0.2),
    "generator_A_test":ImageDataGenerator(),
    "generator_B_test":ImageDataGenerator(),
    "target_size_A":(224,224),
    "target_size_B":(224,224),
    "model_A_struct_path":"/data/mml/overlap_v2_datasets/animal_3/party_A/models/model_struct/EfficientNetB3_224_224.h5",
    "model_A_weight_path":"/data/mml/overlap_v2_datasets/animal_3/party_A/models/model_weights/model_weight_023_0.8618.h5",
    "model_B_struct_path":"/data/mml/overlap_v2_datasets/animal_3/party_B/models/model_struct/EfficientNetB3_224_224_poolingMax.h5",
    "model_B_weight_path":"/data/mml/overlap_v2_datasets/animal_3/party_B/models/model_weights/model_weight_009_0.9927.h5",
    "local_to_global_party_A_path":"exp_data/animal_3/LocalToGlobal/local_to_gobal_party_A.data",
    "local_to_global_party_B_path":"exp_data/animal_3/LocalToGlobal/local_to_gobal_party_B.data",
    "dataset_A_train_path":"/data/mml/overlap_v2_datasets/animal_3/party_A/dataset_split/train",
    "dataset_B_train_path":"/data/mml/overlap_v2_datasets/animal_3/party_B/dataset_split/train",
    "sampled_common_path":"exp_data/animal_3/sampling/num/random",
    "combination_model_path":"/data/mml/overlap_v2_datasets/animal_3/merged_model/combination_model_inheritWeights.h5",
    "stu_model_path":"/data/mml/overlap_v2_datasets/animal_3/merged_model/DenseNet121_224_224_claNum_9.h5",
    "combiantion_lr":0.0005,
    "save_retrainResult_path":"exp_data/animal_3/retrainResult/num/CFL"
}